// Generated by scripts/gen_chisel_wrapper.py (route 3). DO NOT EDIT.
// Wraps XLS-generated Verilog: Ingress_pipeline.v (module Ingress_pipeline)
//
// Chisel 口径：chisel 7.15.0 / scala 2.13.16（与 ../HardwareDesign 对齐）。
// 使用方式：把本文件与对应 .v 一起交给 Chisel 构建（BB 与同名 Verilog
// 模块链接），或在综合流程里把 .v 作为附加源文件。实例化 Shell 类即可，
// 隐式时钟/复位已自动接线：
//   val dut = Module(new IngressPipeline)
//   dut.io.<port> := ...
package p4xlsrtl

import chisel3._
import chisel3.util._

/** BlackBox：与 Verilog module `Ingress_pipeline` 端口 1:1 对应。 */
final class IngressPipelineBlackBox extends BlackBox {
  override def desiredName: String = "Ingress_pipeline"
  val io = IO(new Bundle {
    val clk = Input(Clock())
    val rst = Input(Bool())
    val pkt_in = Input(UInt(512.W))
    val pkt_in_vld = Input(Bool())
    val tbl_mac_table_rsp = Input(UInt(6.W))
    val tbl_mac_table_rsp_vld = Input(Bool())
    val tbl_route_table_rsp = Input(UInt(102.W))
    val tbl_route_table_rsp_vld = Input(Bool())
    val pkt_out_rdy = Input(Bool())
    val ex_portBytes = Output(UInt(256.W))
    val ex_portBytes_vld = Output(Bool())
    val ex_fwdCnt = Output(UInt(128.W))
    val ex_fwdCnt_vld = Output(Bool())
    val tbl_mac_table_key = Output(UInt(48.W))
    val tbl_mac_table_key_vld = Output(Bool())
    val tbl_route_table_key = Output(UInt(40.W))
    val tbl_route_table_key_vld = Output(Bool())
    val pkt_out = Output(UInt(500.W))
    val pkt_out_vld = Output(Bool())
  })
}

/** 友好外壳：隐式时钟/复位自动接线，数据端口 1:1 直连。 */
final class IngressPipeline extends Module {
  val io = IO(new Bundle {
    val pkt_in = Input(UInt(512.W))
    val pkt_in_vld = Input(Bool())
    val tbl_mac_table_rsp = Input(UInt(6.W))
    val tbl_mac_table_rsp_vld = Input(Bool())
    val tbl_route_table_rsp = Input(UInt(102.W))
    val tbl_route_table_rsp_vld = Input(Bool())
    val pkt_out_rdy = Input(Bool())
    val ex_portBytes = Output(UInt(256.W))
    val ex_portBytes_vld = Output(Bool())
    val ex_fwdCnt = Output(UInt(128.W))
    val ex_fwdCnt_vld = Output(Bool())
    val tbl_mac_table_key = Output(UInt(48.W))
    val tbl_mac_table_key_vld = Output(Bool())
    val tbl_route_table_key = Output(UInt(40.W))
    val tbl_route_table_key_vld = Output(Bool())
    val pkt_out = Output(UInt(500.W))
    val pkt_out_vld = Output(Bool())
  })
  private val bb = Module(new IngressPipelineBlackBox)
  bb.io.clk := clock
  bb.io.rst := reset.asBool
  bb.io.pkt_in := io.pkt_in
  bb.io.pkt_in_vld := io.pkt_in_vld
  bb.io.tbl_mac_table_rsp := io.tbl_mac_table_rsp
  bb.io.tbl_mac_table_rsp_vld := io.tbl_mac_table_rsp_vld
  bb.io.tbl_route_table_rsp := io.tbl_route_table_rsp
  bb.io.tbl_route_table_rsp_vld := io.tbl_route_table_rsp_vld
  bb.io.pkt_out_rdy := io.pkt_out_rdy
  io.ex_portBytes := bb.io.ex_portBytes
  io.ex_portBytes_vld := bb.io.ex_portBytes_vld
  io.ex_fwdCnt := bb.io.ex_fwdCnt
  io.ex_fwdCnt_vld := bb.io.ex_fwdCnt_vld
  io.tbl_mac_table_key := bb.io.tbl_mac_table_key
  io.tbl_mac_table_key_vld := bb.io.tbl_mac_table_key_vld
  io.tbl_route_table_key := bb.io.tbl_route_table_key
  io.tbl_route_table_key_vld := bb.io.tbl_route_table_key_vld
  io.pkt_out := bb.io.pkt_out
  io.pkt_out_vld := bb.io.pkt_out_vld
}

