// Generated by scripts/gen_chisel_wrapper.py (route 3). DO NOT EDIT.
// Wraps XLS-generated Verilog: Ingress_pipeline__parser.v (module Ingress_pipeline__parser)
//
// Chisel 口径：chisel 7.15.0 / scala 2.13.16（与 ../HardwareDesign 对齐）。
// 使用方式：把本文件与对应 .v 一起交给 Chisel 构建（BB 与同名 Verilog
// 模块链接），或在综合流程里把 .v 作为附加源文件。实例化 Shell 类即可，
// 隐式时钟/复位已自动接线：
//   val dut = Module(new IngressPipelineParser)
//   dut.io.<port> := ...
package p4xlsrtl

import chisel3._
import chisel3.util._

/** BlackBox：与 Verilog module `Ingress_pipeline__parser` 端口 1:1 对应。 */
final class IngressPipelineParserBlackBox extends BlackBox {
  override def desiredName: String = "Ingress_pipeline__parser"
  val io = IO(new Bundle {
    val clk = Input(Clock())
    val rst = Input(Bool())
    val pkt_in = Input(UInt(512.W))
    val pkt_in_vld = Input(Bool())
    val ph_0_rdy = Input(Bool())
    val ph_0 = Output(UInt(680.W))
    val ph_0_vld = Output(Bool())
  })
}

/** 友好外壳：隐式时钟/复位自动接线，数据端口 1:1 直连。 */
final class IngressPipelineParser extends Module {
  val io = IO(new Bundle {
    val pkt_in = Input(UInt(512.W))
    val pkt_in_vld = Input(Bool())
    val ph_0_rdy = Input(Bool())
    val ph_0 = Output(UInt(680.W))
    val ph_0_vld = Output(Bool())
  })
  private val bb = Module(new IngressPipelineParserBlackBox)
  bb.io.clk := clock
  bb.io.rst := reset.asBool
  bb.io.pkt_in := io.pkt_in
  bb.io.pkt_in_vld := io.pkt_in_vld
  bb.io.ph_0_rdy := io.ph_0_rdy
  io.ph_0 := bb.io.ph_0
  io.ph_0_vld := bb.io.ph_0_vld
}

