// Generated by scripts/gen_chisel_wrapper.py (route 3). DO NOT EDIT.
// Wraps XLS-generated Verilog: Ingress_pipeline__deparser.v (module Ingress_pipeline__deparser)
//
// Chisel 口径：chisel 7.15.0 / scala 2.13.16（与 ../HardwareDesign 对齐）。
// 使用方式：把本文件与对应 .v 一起交给 Chisel 构建（BB 与同名 Verilog
// 模块链接），或在综合流程里把 .v 作为附加源文件。实例化 Shell 类即可，
// 隐式时钟/复位已自动接线：
//   val dut = Module(new IngressPipelineDeparser)
//   dut.io.<port> := ...
package p4xlsrtl

import chisel3._
import chisel3.util._

/** BlackBox：与 Verilog module `Ingress_pipeline__deparser` 端口 1:1 对应。 */
final class IngressPipelineDeparserBlackBox extends BlackBox {
  override def desiredName: String = "Ingress_pipeline__deparser"
  val io = IO(new Bundle {
    val clk = Input(Clock())
    val rst = Input(Bool())
    val ph_2 = Input(UInt(680.W))
    val ph_2_vld = Input(Bool())
    val pkt_out_rdy = Input(Bool())
    val ph_2_rdy = Output(Bool())
    val pkt_out = Output(UInt(500.W))
    val pkt_out_vld = Output(Bool())
  })
}

/** 友好外壳：隐式时钟/复位自动接线，数据端口 1:1 直连。 */
final class IngressPipelineDeparser extends Module {
  val io = IO(new Bundle {
    val ph_2 = Input(UInt(680.W))
    val ph_2_vld = Input(Bool())
    val pkt_out_rdy = Input(Bool())
    val ph_2_rdy = Output(Bool())
    val pkt_out = Output(UInt(500.W))
    val pkt_out_vld = Output(Bool())
  })
  private val bb = Module(new IngressPipelineDeparserBlackBox)
  bb.io.clk := clock
  bb.io.rst := reset.asBool
  bb.io.ph_2 := io.ph_2
  bb.io.ph_2_vld := io.ph_2_vld
  bb.io.pkt_out_rdy := io.pkt_out_rdy
  io.ph_2_rdy := bb.io.ph_2_rdy
  io.pkt_out := bb.io.pkt_out
  io.pkt_out_vld := bb.io.pkt_out_vld
}

