#!/usr/bin/env python3
"""gen_chisel_wrapper.py —— 路线 3：XLS 生成的 Verilog 原样封装成 Chisel BlackBox。

对每个输入的 .v 文件（XLS codegen 产物，单 top module）生成一个 .scala：

  1. BlackBox 类   —— 端口 1:1 映射（clk/rst 显式暴露），desiredName 指向
                      Verilog module 名。firtool 链接时与同名 Verilog 模块对接。
  2. Shell 类      —— 友好外壳（普通 chisel3.Module）：隐式时钟/复位自动接线，
                      其余端口 1:1 直连，下游像用普通 Chisel 模块一样实例化。

用法：
  scripts/gen_chisel_wrapper.py -o out/a2/chisel out/a2/demo9-l3forwarder.v [...]

自检（生成后自动执行）：BB 的 io 字段数 == Verilog 端口数；Shell 连线语句数
== 端口数 - 2（clk/rst 隐式）。

边界与假设：
  - 一个 .v 只含一个 module（XLS driver 单 top 产出），多 module 报错退出；
  - 端口名必须是合法 Scala 标识符且非保留字（XLS 的 chan 名满足；检查到
    冲突立即报错，不做静默改名）；
  - 仅支持 `input/output wire [H:L] name` 形式（XLS 输出形态），不支持
    reg 端口 / 参数化模块 / 多维端口。
"""

import argparse
import pathlib
import re
import sys

# Scala/chisel3 常见保留字与易冲突名（端口名撞上即报错，提示手动处理）
RESERVED = {
    "abstract", "case", "catch", "class", "def", "do", "else", "extends",
    "false", "final", "finally", "for", "if", "implicit", "import", "lazy",
    "match", "new", "null", "object", "override", "package", "private",
    "protected", "return", "sealed", "super", "this", "throw", "trait",
    "true", "try", "type", "val", "var", "while", "with", "yield",
    "clone", "eq", "notify", "wait", "getClass", "hashCode", "toString",
}

MOD_RE = re.compile(r"^\s*module\s+(\w+)\s*\(")
PORT_RE = re.compile(
    r"^\s*(input|output)\s+(?:wire|reg)\s*(?:\[\s*(\d+)\s*:\s*(\d+)\s*\])?\s*(\w+)\s*,?\s*$")


class Port:
    def __init__(self, direction: str, width: int, name: str):
        self.direction = direction  # "input" | "output"
        self.width = width
        self.name = name

    @property
    def is_clk(self) -> bool:
        return self.name == "clk"

    @property
    def is_rst(self) -> bool:
        return self.name == "rst"


def parse_module(text: str, path: str, top: str | None = None):
    """返回 (module 名, [Port])。

    top=None：要求文件恰好一个 module（旧口径）。
    top 指定：多模块文件（多 proc 网络）里选 `module <top>(` 的那个 ——
    BlackBox 包的是**顶层**端口；子 proc 模块在文件里仅作为参考。
    """
    mods = []
    cur = None  # (name, [raw port lines])
    for lineno, line in enumerate(text.splitlines(), 1):
        m = MOD_RE.match(line)
        if m and cur is None:
            cur = (m.group(1), [])
            continue
        if cur is not None:
            if line.strip().startswith(")"):
                mods.append(cur)
                cur = None
                continue
            cur[1].append((lineno, line))
    if not mods:
        raise SystemExit(f"{path}: 未找到 module 声明")
    if top is not None:
        mods = [m for m in mods if m[0] == top]
        if not mods:
            raise SystemExit(f"{path}: 未找到 top module '{top}'"
                             f"（文件里有：{', '.join(m[0] for m in mods[:1])} 等）")
    elif len(mods) > 1 or cur is not None:
        raise SystemExit(f"{path}: 期望单 module（发现 {len(mods) + (1 if cur is not None else 0)} 个）"
                         "；多模块文件请用 --top 指定顶层")

    name, raws = mods[0]
    ports = []
    for lineno, line in raws:
        m = PORT_RE.match(line)
        if not m:
            if line.strip():
                raise SystemExit(f"{path}:{lineno}: 无法解析端口行（仅支持 input/output wire）：{line.strip()}")
            continue
        direction, hi, lo, pname = m.groups()
        width = (int(hi) - int(lo) + 1) if hi is not None else 1
        if pname in RESERVED:
            raise SystemExit(f"{path}:{lineno}: 端口名 '{pname}' 是 Scala 保留字，需手动处理")
        ports.append(Port(direction, width, pname))
    if not ports:
        raise SystemExit(f"{path}: module {name} 无端口")
    return name, ports


def chisel_io_line(p: Port) -> str:
    if p.is_clk:
        return f"    val {p.name} = Input(Clock())"
    if p.is_rst:
        return f"    val {p.name} = Input(Bool())"
    t = f"UInt({p.width}.W)" if p.width > 1 else "Bool()"
    d = "Input" if p.direction == "input" else "Output"
    return f"    val {p.name} = {d}({t})"


def pascal(stem: str) -> str:
    parts = re.split(r"[^0-9a-zA-Z]+", stem)
    joined = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not joined or not (joined[0].isalpha() or joined[0] == "_"):
        joined = "_" + joined
    return joined


def emit(verilog_path: pathlib.Path, out_dir: pathlib.Path, top: str | None = None) -> pathlib.Path:
    text = verilog_path.read_text(encoding="utf-8")
    mod_name, ports = parse_module(text, str(verilog_path), top)
    cls = pascal(verilog_path.stem)

    data_ports = [p for p in ports if not p.is_clk and not p.is_rst]
    has_clk = any(p.is_clk for p in ports)
    has_rst = any(p.is_rst for p in ports)
    if not (has_clk and has_rst):
        raise SystemExit(f"{verilog_path}: 缺少 clk/rst 端口（XLS proc 产物应自带）")

    b = []
    b.append("// Generated by scripts/gen_chisel_wrapper.py (route 3). DO NOT EDIT.")
    b.append(f"// Wraps XLS-generated Verilog: {verilog_path.name} (module {mod_name})")
    b.append("//")
    b.append("// 使用方式：把本文件与对应 .v 一起交给 Chisel 构建（BB 与同名 Verilog")
    b.append("// 模块链接），或在综合流程里把 .v 作为附加源文件。实例化 Shell 类即可，")
    b.append("// 隐式时钟/复位已自动接线：")
    b.append(f"//   val dut = Module(new {cls})")
    b.append("//   dut.io.<port> := ...")
    b.append("package p4xlsrtl")
    b.append("")
    b.append("import chisel3._")
    b.append("import chisel3.util._")
    b.append("")
    b.append(f"/** BlackBox：与 Verilog module `{mod_name}` 端口 1:1 对应。 */")
    b.append(f"final class {cls}BlackBox extends BlackBox {{")
    b.append("  override def desiredName: String = \"" + mod_name + "\"")
    b.append("  val io = IO(new Bundle {")
    for p in ports:
        b.append(chisel_io_line(p))
    b.append("  })")
    b.append("}")
    b.append("")
    b.append(f"/** 友好外壳：隐式时钟/复位自动接线，数据端口 1:1 直连。 */")
    b.append(f"final class {cls} extends Module {{")
    b.append("  val io = IO(new Bundle {")
    for p in data_ports:
        b.append(chisel_io_line(p))
    b.append("  })")
    b.append(f"  private val bb = Module(new {cls}BlackBox)")
    b.append("  bb.io.clk := clock")
    b.append("  bb.io.rst := reset.asBool")
    for p in data_ports:
        if p.direction == "input":
            b.append(f"  bb.io.{p.name} := io.{p.name}")
    for p in data_ports:
        if p.direction == "output":
            b.append(f"  io.{p.name} := bb.io.{p.name}")
    b.append("}")
    b.append("")

    out_path = out_dir / f"{cls}.scala"
    out_path.write_text("\n".join(b) + "\n", encoding="utf-8")
    return out_path


def self_check(scala_path: pathlib.Path, ports) -> None:
    """结构自检：BB 与 Shell 的 io 字段数、clk/rst、Shell 连线数。失败抛异常。"""
    t = scala_path.read_text(encoding="utf-8")
    data_ports = [p for p in ports if not p.is_clk and not p.is_rst]
    shell_idx = t.index("/** 友好外壳")
    bb_part, shell_part = t[:shell_idx], t[shell_idx:]

    def count_fields(part: str) -> int:
        return len(re.findall(r"^\s+val \w+ = (?:Input|Output)\(", part, re.M))

    if count_fields(bb_part) != len(ports):
        raise SystemExit(f"{scala_path}: 自检失败 BB io {count_fields(bb_part)} != {len(ports)}")
    if count_fields(shell_part) != len(data_ports):
        raise SystemExit(f"{scala_path}: 自检失败 Shell io {count_fields(shell_part)} != {len(data_ports)}")
    links = len(re.findall(r"^\s+(?:bb\.io\.\w+ := |io\.\w+ := bb\.io\.\w+)", t, re.M))
    expect_links = len(ports)  # clk/rst 各 1 + 数据端口各 1
    if links != expect_links:
        raise SystemExit(f"{scala_path}: 自检失败连线 {links} != {expect_links}")
    if "extends BlackBox" not in t or "extends Module" not in t:
        raise SystemExit(f"{scala_path}: 自检失败 缺 BlackBox/Module")


def main() -> int:
    ap = argparse.ArgumentParser(description="XLS Verilog -> Chisel BlackBox wrapper（路线 3）")
    ap.add_argument("-o", "--out-dir", required=True, help="输出目录")
    ap.add_argument("--top", default=None,
                    help="多模块文件（多 proc 网络）里作为 BlackBox 的顶层 module 名；"
                         "缺省要求文件恰好一个 module")
    ap.add_argument("verilogs", nargs="+", help="XLS 生成的 .v 文件")
    args = ap.parse_args()

    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    ok = 0
    for v in args.verilogs:
        vp = pathlib.Path(v)
        if not vp.exists():
            print(f"❌ {v}: 文件不存在", file=sys.stderr)
            return 1
        scala = emit(vp, out_dir, args.top)
        name, ports = parse_module(vp.read_text(encoding="utf-8"), v, args.top)
        self_check(scala, ports)
        data = sum(1 for p in ports if not p.is_clk and not p.is_rst)
        print(f"✅ {vp.name} (module {name}, {len(ports)} 端口) -> {scala} "
              f"[BB io={len(ports)}, Shell 数据端口={data}]")
        ok += 1
    print(f"共 {ok} 个 wrapper，全部通过自检")
    return 0


if __name__ == "__main__":
    sys.exit(main())
